[[appendix_activemq]]
[appendix]
== Apache ActiveMQ

[role="lead"]
In this appendix, we describe how to install and configure Apache ActiveMQ to
support STOMP and MQTT protocols.

=== Download and Installation

Apache ActiveMQ latest release can be downloaded for its
http://activemq.apache.org/activemq-580-release.html[download page] and the
http://activemq.apache.org/getting-started.html[getting started page] contains all the information to install it.

For our setup, ActiveMQ will be installed in the directory +~/mobilewebmsg/mybroker+.

Once you have download the archive for ActiveMQ, it can be installed and started by running the commands:

[source,sh]
----
$ tar zxvf apache-activemq-5.8.0-bin.tar.gz
$ cd apache-activemq-5.8.0
$ mkdir ~/mobilewebmsg/
$ ./bin/activemq create ~/mobilewebmsg/mybroker
...
$ cd ~/mobilewebmsg/mybroker
$ ./bin/mybroker start
...
$ tail data/activemq.log
...
2013-06-14 19:44:52,801 | INFO  | Apache ActiveMQ 5.8.0 (mybroker, ID:retsina.local-53410-1371231892651-0:1) started | org.apache.activemq.broker.BrokerService | main
...
----

To stop he broker, run the following command:

[source,sh]
----
$ ./bin/mybroker stop
...
Stopping broker: mybroker
.... FINISHED
----

[[app_activemq_security]]
=== Security Configuration

Out of the box, ActiveMQ does not provide any security authentication on its connections. While it makes it simple to test it, this is not a good practice
and we will activate a very simple authentication mechanism.

Edit the +conf/activemq.xml+ file to add a +plugins+ element after the +managemementContext+ element:

[source,sh]
----
$ cd ~/mobilewebmsg/mybroker
$ vim ./conf/activemq.xml
...
<managementContext>
   ...
</managementContext>
<plugins>
    <!-- Configure authentication; Username, passwords and groups -->
    <simpleAuthenticationPlugin>
        <users>
            <authenticationUser username="system"
                                password="${activemq.password}"
                                groups="users,admins"/>
            <authenticationUser username="user"
                                password="${guest.password}"
                                groups="users"/>
            <authenticationUser username="guest"
                                password="${guest.password}"
                                groups="guests"/>
        </users>
    </simpleAuthenticationPlugin>

    <!--  Lets configure a destination based authorization mechanism -->
    <authorizationPlugin>
      <map>
        <authorizationMap>
          <authorizationEntries>
            <authorizationEntry queue=">"
                                read="users"
                                write="users"
                                admin="users" />
            <authorizationEntry topic=">"
                                read="users"
                                write="users"
                                admin="users" />
            <authorizationEntry topic="ActiveMQ.Advisory.>"
                                read="guests,users"
                                write="guests,users"
                                admin="guests,users"/>
          </authorizationEntries>
        </authorizationMap>
      </map>
    </authorizationPlugin>

    <!-- This plugin allows to use / as a destination path separator -->
    <destinationPathSeparatorPlugin />
</plugins>
...
----

We restart the broker to update its configuration

[source,sh]
----
$ ./bin/mybroker restart
...

ActiveMQ is running (pid '6664')
----

With this setting, only authenticated user identified by the name +user+ and the password +password+ will be able to connect to ActiveMQ.

[[app_activemq_stomp]]
=== STOMP Configuration

STOMP protocol is enabled in ActiveMQ by adding a transport connector to its configuration (as explained in full details in its
http://activemq.apache.org/stomp.html[STOMP configuration]).

Edit the +conf/activemq.xml+ file to add a +transport+ connector for STOMP:

[source,sh]
----
$ cd ~/mobilewebmsg/mybroker
$ vim ./conf/activemq.xml
...
<transportConnectors>
   ...
   <transportConnector name="stomp" uri="stomp://localhost:61613"/>
   ...
</transportConnectors>
----

After ActiveMQ is restarted, it accepts STOMP connections at the URL +stomp://localhost:61613+.

[source,sh]
----
$ ./bin/mybroker restart
...
ActiveMQ is running (pid '6664')
$ tail data/activemq.log
...
2013-06-14 19:44:52,797 | INFO  | Listening for connections at: stomp://localhost:61613 | org.apache.activemq.transport.TransportServerThreadSupport | main
2013-06-14 19:44:52,797 | INFO  | Connector stomp Started | org.apache.activemq.broker.TransportConnector | main
...
----

[[app_activemq_mqtt]]
=== MQTT Configuration

Like for STOMP, MQTT protocol can be added to ActiveMQ by adding a transport connector to its configuration (as explained in full details in its
http://activemq.apache.org/mqtt.html[MQTT configuration]).

[source,sh]
----
$ cd ~/mobilewebmsg/mybroker
$ vim ./conf/activemq.xml
...
<transportConnectors>
    ...
    <transportConnector name="mqtt" uri="mqtt://localhost:1883"/>
    ...
</transportConnectors>
$ ./bin/mybroker restart
...
ActiveMQ is running (pid '6664')
----

After ActiveMQ is restarted, it accepts MQTT connections at the URL +mqtt://localhost:1883+.

[source,sh]
----
2013-06-14 19:44:52,799 | INFO  | Listening for connections at: mqtt://localhost:1883 | org.apache.activemq.transport.TransportServerThreadSupport | main
2013-06-14 19:44:52,800 | INFO  | Connector mqtt Started | org.apache.activemq.broker.TransportConnector | main
----

[[app_activemq_websockets]]
=== Web Sockets Configuration

The Web Sockets  protocol is enabled in ActiveMQ by adding a transport connector to its configuration (as explained in full details in its
http://activemq.apache.org/websockets.html[Web Sockets configuration page]).

[source,sh]
----
$ vim ./conf/activemq.xml
...
<transportConnectors>
   ...
   <transportConnector name="websocket" uri="ws://0.0.0.0:61614"/>
   ...
</transportConnectors>
----

After ActiveMQ is restarted, it accepts Web Sockets connection at the URL +ws://0.0.0.0:61614+.

[source,sh]
----
2013-06-14 19:55:01,490 | INFO  | Connector websocket Started | org.apache.activemq.broker.TransportConnector | main
----
