== Mobile Messaging

[role="lead"]
In this chapter, we present some challenges offered by mobile devices and their
specific constraints. We highlight how messaging protocols can alleviate these
constraints and are well suited for mobile applications.

=== Mobile Challenges

Mobile devices (such as smartphones, tablets, to a lesser extent portable consoles) differs in many ways from desktop devices.

Their "mobility" introduces constraints that were not present in desktop devices.

Mobile devices are running on battery. If applications consume less energy, the mobile device can save battery and extend their charges.
Mobile devices are often connected using Wifi and suffer from intermittent loss of connectivity. In my own house, there are some specific places where I can not 
connect to my local Wifi network and my table loses its network connectivity when I move from one romm to another if I go through this places. If applications are resilient to 
network loss (or intermittent disconnection), they provide a better user experience.

